name: Docker CI

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push payment frontend (multi-arch)
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile.frontend
        platforms: linux/amd64,linux/arm64
        push: true
        tags: palani1703/payment-frontend:latest

    - name: Build and push payment backend (multi-arch)
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile.backend
        platforms: linux/amd64,linux/arm64
        push: true
        tags: palani1703/payment-backend:latest
